#配置数据库的连接信息
spring:
  application:
    name: demo1
  datasource:
    url: jdbc:mysql://localhost:3306/tlias
    username: root
    password: dinghuaye521
    driver-class-name: com.mysql.cj.jdbc.Driver


#mybatis的相关配置
mybatis:
  configuration:
      map-underscore-to-camel-case: true
      log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
